app/models.py
#-*-coding:utf-8-*-
from . import db

class BookClass(db.Model):
    __tablename__ = 'ishare_book_class'
    bookClassId=db.Column('book_class_id',db.Integer,primary_key=True)
    bookClassName=db.Column('book_class_name',db.String(255),index=True)
    bookParentClassId=db.Column('book_parent_class_id',db.Integer)
    bookClassDesc=db.Column('book_class_desc',db.String(255))
    bookClassOrder=db.Column('book_class_order',db.Integer)
    createBy=db.Column('create_by',db.String(64))
    createDate=db.Column('create_date',db.DateTime())
    updateBy=db.Column('update_by',db.String(64))
    updateDate=db.Column('update_date',db.DateTime())
    remarks=db.Column('remarks',db.String(255))
    delFlag=db.Column('del_flag',db.String(1))
    books=db.relationship('Book', secondary='ishare_book_class_rela',backref=db.backref('book', lazy='dynamic'), lazy='dynamic')

class Book(db.Model):
    __tablename__ = 'ishare_book'
    bookId=db.Column('book_id',db.Integer,primary_key=True)
    bookName=db.Column('book_name',db.String(100),index=True)
    bookAuthor=db.Column('book_author',db.String(100))
    bookPress=db.Column('book_press',db.String(255))
    bookPressDate=db.Column('book_pressdate',db.String(20))
    bookIsbn=db.Column('book_isbn',db.String(50))
    bookContentDesc=db.Column('book_content_desc',db.Text)
    bookAuthorDesc=db.Column('book_author_desc',db.Text)
    bookCatalog=db.Column('book_catalog',db.Text)
    bookImage=db.Column('book_image',db.String(255))
    bookPrice=db.Column('book_price',db.String(20))
    bookTag = db.Column('book_tag',db.String(500))
    bookClassId=db.Column('book_class_id',db.Integer)
    bookIshot=db.Column('book_ishot',db.Integer)
    bookShoworder=db.Column('book_showorder',db.Integer)
    bookFloorId=db.Column('book_floor_id',db.Integer)
    bookAddDate=db.Column('book_add_date',db.DateTime())
    bookWantread_count=db.Column('book_wantread_count',db.Integer)
    bookIsreadCount=db.Column('book_isread_count',db.Integer)
    bookHavereadCount=db.Column('book_haveread_count',db.Integer)
    bookEbookHavecount=db.Column('book_ebook_havecount',db.Integer)
    bookBookHavecount=db.Column('book_book_havecount',db.Integer)
    bookShareEbookcount=db.Column('book_share_ebookcount',db.Integer)
    bookShareBookcount=db.Column('book_share_bookcount',db.Integer)
    bookPages=db.Column('book_pages',db.String(11))
    bookDoubanId = db.Column('book_douban_id',db.String(11))
    bookDoubanUrl=db.Column('book_douban_url',db.String(255))
    bookStatus=db.Column('book_status',db.Integer)
    createBy=db.Column('create_by',db.String(64))
    createDate=db.Column('create_date',db.DateTime())
    updateBy=db.Column('update_by',db.String(64))
    updateDate = db.Column('update_date',db.DateTime())
    remarks = db.Column('remarks',db.String(255))
    delFlag= db.Column('del_flag',db.String(1))
    bookClasses = db.relationship('BookClass', secondary='ishare_book_class_rela',backref=db.backref('bookclass', lazy='dynamic'),lazy='dynamic')


class BookClassRela(db.Model):
    __tablename__ = 'ishare_book_class_rela'
    bookId=db.Column('book_id',db.Integer,db.ForeignKey('ishare_book.book_id'),primary_key=True)
    bookClassId = db.Column('book_class_id', db.Integer,db.ForeignKey('ishare_book_class.book_class_id'),primary_key=True)
    createBy = db.Column('create_by', db.String(64))
    createDate = db.Column('create_date', db.DateTime())
    updateBy = db.Column('update_by', db.String(64))
    updateDate = db.Column('update_date', db.DateTime())
    remarks = db.Column('remarks', db.String(255))
    delFlag = db.Column('del_flag', db.String(1))

app/main/forms.py
#-*-coding:utf-8-*-
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField


class SearchForm(FlaskForm):
    searchInfo=StringField('')
    submit=SubmitField('搜索')

app/__init__.py
#-*-coding:utf-8-*-
from flask import Flask,render_template
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_sqlalchemy import SQLAlchemy
from flask_caching import Cache
from config import config

bootstrap=Bootstrap()
mail=Mail()
db=SQLAlchemy()
cache=Cache()


def create_app(config_name):
    app=Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    bootstrap.init_app(app)
    mail.init_app(app)
    db.init_app(app)
    cache.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .book import book_blueprint
    app.register_blueprint(book_blueprint,url_prefix='/book')
    from .auth import auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

app/book/__init__.py
#-*-coding:utf-8-*-
from flask import Blueprint

book_blueprint=Blueprint('book_blueprint',__name__)

from . import views

app/book/views.py
#-*-coding:utf-8-*-
from flask import render_template,session,redirect,url_for,abort,flash,request,current_app,make_response
from . import book_blueprint
from ..models import BookClass,Book
from .. import db
from app.common import getBookClassByParentId,getBookClassById

@book_blueprint.route('/booklist',methods=['GET','POST'])
def booklist():
    bookClassList=getBookClassByParentId(0)
    bookClassId=request.args.get('bookClassId',type=int)
    subBookClassId=request.args.get('subBookClassId',type=int)
    per_page=current_app.config['ISHAREREAD_BOOKLIST_PER_PAGE']
    page = request.args.get('page', 1, type=int)
    subBookClassList=[]
    if bookClassId and subBookClassId:
        subBookClassList = getBookClassByParentId(bookClassId)
        pagination = Book.query.join(BookClass.bookclass).filter(BookClass.bookClassId == subBookClassId).paginate(page,per_page=per_page,error_out=False)
    elif bookClassId:
        subBookClassList = getBookClassByParentId(bookClassId)
        pagination = Book.query.join(BookClass.bookclass).filter(BookClass.bookParentClassId == bookClassId).paginate(page, per_page=per_page, error_out=False)
    else:
        pagination=Book.query.join(BookClass.bookclass).paginate(page,per_page=per_page,error_out=False)
    bookList=pagination.items
    return render_template('book/booklist.html',bookClassId=bookClassId,subBookClassId=subBookClassId,
                           bookClassList=bookClassList,subBookClassList=subBookClassList,
                           bookList=bookList,pagination=pagination)



@book_blueprint.route('/book/<int:bookId>',methods=['GET','POST'])
def getbookdetail(bookId):
    book=Book.query.filter(Book.bookId==bookId).first()
    bookClass=book.bookClasses.first()
    if bookClass:
        parentBookClass=getBookClassById(bookClass.bookParentClassId)
        sameTypeBooks=Book.query.join(BookClass.bookclass).filter(BookClass.bookClassId == bookClass.bookClassId,Book.bookId!=bookId).limit(5)
    return render_template('book/book.html',parentBookClass=parentBookClass,bookClass=bookClass,book=book,sameTypeBooks=sameTypeBooks)

app/main/__init__.py
#-*-coding:utf-8-*-
from flask import Blueprint

main=Blueprint('main',__name__)

from . import views,errors

app/main/views.py
#-*-coding:utf-8-*-
from flask import render_template,session,redirect,url_for,abort,flash,request,current_app,make_response
from app.common import getBookClassByParentId
from . import main
from .forms import SearchForm
from ..models import Book
from .. import db

@main.route('/',methods=['GET','POST'])
def index():
    form=SearchForm()
    bookClassList=getBookClassByParentId(0)
    newBooks=Book.query.filter_by(bookStatus=1).order_by(Book.createBy.desc()).limit(5)
    goodBooks=Book.query.filter(Book.bookStatus==1,Book.bookFloorId==1).order_by(Book.bookShoworder).limit(10)
    shareHotBooks=Book.query.filter_by(bookStatus=1).order_by(Book.bookShareEbookcount.desc()).limit(5)
    return render_template('index.html',form=form,bookClassList=bookClassList,
                           newBooks=newBooks,goodBooks=goodBooks,shareHotBooks=shareHotBooks)

app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint, fragment='') %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% block title %}爱分享读书{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
<link href="https://v3.bootcss.com/examples/carousel/carousel.css" rel="stylesheet">
{% endblock %}

{% block navbar %}

<nav class="navbar navbar-inverse navbar-fixed-top">
<div class="container">
<div class="navbar-header">
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="{{ url_for('main.index') }}">IshareRead</a>
</div>
 <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">首页</a></li>
                <li><a href="{{ url_for('book_blueprint.booklist') }}">分类</a></li>
                <li><a href="{{ url_for('main.index') }}">排行</a></li>
            </ul>
            <!--
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="">
                        用户名 <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">修改密码</a></li>
                        <li><a href="#">修改邮箱</a></li>
                        <li><a href="#">登出</a></li>
                    </ul>
                </li>

                <li><a href="#">Log In</a></li>
            </ul>
            -->
            <form class="navbar-form navbar-right">
                <div class="input-group">
                    <div class="form-group">
                      <input type="text" placeholder="书名" class="form-control">
                    </div>
                    <span class="input-group-btn">
                    <button type="submit" class="btn btn-default">搜索</button>
                    </span>
                </div>
            </form>
   </div>
  </div>
</nav>
<div class="navbar navbar-inverse ">
</div>
{% endblock %}
{% block content %}

<div class="container">

{% block page_content %} {% endblock %}

    <hr>
    <footer>
        <div class="container">
            <div class="row"><div class="col-md-12"></div></div>
            <div class="row">
                <div class="col-md-6 ">
                 <p>    关于我们	在线客服	帮助与支持	联系我们	免责声明   </p>
                 <p>&copy; 2014-2019 爱分享读书 网站备案号 : ( 湘ICP备13012731号-3 )</p>

                    <p> 邮箱:<a href="mailto:master@ishareread.com‍">master@ishareread.com</a> | QQ群:415319375 |微博:@爱分享读书</p>

                <p>推荐浏览器：Internet Explorer 8及以上 </p>
                </div>
                <div class="col-md-6">
                    <div class="pull-right">
                      <img width="120px" height="120px" src="http://image.ishareread.com/qrcode_for_gh_70fb5d85a824_258.jpg"  alt="微信公众号" >
                    </div>
                </div>

            </div>
        </div>
    </footer>

</div>


{% endblock %}

app/templates/book/book.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
<div class="row row-offcanvas row-offcanvas-right">
 <div class="col-md-8">
     <div class="panel panel-default">
       <div class="panel-heading">
           <div class="panel-title">
               当前位置：
               {% if parentBookClass %}
               <a href="{{ url_for('book_blueprint.booklist',bookClassId=parentBookClass.bookClassId)}}">{{parentBookClass.bookClassName}}</a>
               {% endif %}
               {% if bookClass %}
               >><a href="{{ url_for('book_blueprint.booklist',bookClassId=parentBookClass.bookClassId,subBookClassId=bookClass.bookClassId)}}">{{bookClass.bookClassName}}</a>
               {% endif %}
           </div>
       </div>
       <div class="panel-body">
           <div class="row">
               <div class="col-md-4">
                   <img width="186px" height="250px" src="{{book.bookImage}}" alt="{{book.bookName}}" class="img-thumbnail">
               </div>
               <div class="col-md-8">
                   <h4>{{book.bookName}}</h4>
                   <p>作者：{{book.bookAuthor}}</p>
                   <p>出版社：{{book.bookPress}}</p>
                   <p>出版日期：{{book.bookPressDate}}</p>
                   <p>ISBN：{{book.bookIsbn}}</p>
               </div>
           </div>
           <div class="row">
               <div class="col-md-12">
                   <h4>内容简介</h4>
                   <p>
                       {{book.bookContentDesc|safe}}
                   </p>
               </div>
           </div>
           <div class="row">
               <div class="col-md-12">
                   <h4>作者简介</h4>
                   <p>
                       {{book.bookAuthorDesc|safe}}
                   </p>
               </div>
           </div>
       </div>
    </div>
  </div>
   <div class="col-md-4">
     <div class="panel panel-default">
         <div class="panel-heading">
           <div class="panel-title">
               下载与推送
           </div>
         </div>
         <div class="panel-body">
         </div>
     </div>
      <div class="panel panel-default">
         <div class="panel-heading">
           <div class="panel-title">
               同类好书
           </div>
         </div>
         <div class="panel-body">
             <ul class="sameclassbook_ul">
                {% for book in sameTypeBooks %}
                 <li>
                     <img width="40px" height="55px" src="{{book.bookImage}}" alt="{{book.bookName}}">
                     <div>
                         <p><a href="{{ url_for('book_blueprint.getbookdetail',bookId=book.bookId)}}">{{book.bookName}}</a></p>
                         <p>{{book.bookAuthor}}</p>
                     </div>
                     <p class="dashedline"></p>
                 </li>
                {% endfor %}
             </ul>
         </div>
     </div>
   </div>
 </div>
{% endblock %}

app/templates/book/booklist.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}
{% block page_content %}
<div class="row row-offcanvas row-offcanvas-right">
 <div class="col-md-3">

   <div class="list-group">
        {% for bookClass in bookClassList %}
            <a href="{{ url_for('book_blueprint.booklist',bookClassId=bookClass.bookClassId)}}" class="list-group-item text-center {% if bookClass.bookClassId==bookClassId%}active{% endif%}">{{bookClass.bookClassName}}</a>
        {% endfor %}
   </div>
  </div>
   <div class="col-md-9">
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-title">
                <ul class="subbookclass_ul">
                {% for subBookClass in subBookClassList %}
                    <li><a class="btn-default btn-sm {%if subBookClass.bookClassId==subBookClassId %}active{%endif%}" href="{{ url_for('book_blueprint.booklist',bookClassId=subBookClass.bookParentClassId,subBookClassId=subBookClass.bookClassId)}}">{{subBookClass.bookClassName}}</a></li>
                {% endfor%}
                </ul>
            </div>
        </div>
        <div class="panel-body">
           <ul class="booklist_content">
             {% for book in bookList%}
                <li class="booklist_bookitem" >
                    <a href="{{ url_for('book_blueprint.getbookdetail',bookId=book.bookId)}}">
                         <img width="140px" height="209px" src="{{ book.bookImage }}" alt="{{ book.bookName }}"  class="pull-left" onerror="javascript:this.src='/res/images/nobook.jpg'">
                         <h4>{{ book.bookName }}</h4>
                   </a>
                   <div class="author_container">
                      {{ book.bookAuthor|safe }}
                   </div>
                   <div class="summery">
                      <p>
                        {{ book.bookContentDesc }}
                      </p>
                   </div>

                </li>
             {% endfor %}
           </ul>
       </div>

    </div>
    <div class="booklist_page">
        {% if pagination %}
        <div class="pagination">
            {{ macros.pagination_widget(pagination, 'book_blueprint.booklist',bookClassId=bookClassId,subBookClassId=subBookClassId) }}
        </div>
        {% endif %}
    </div>
   </div>
 </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
  <!-- Main jumbotron for a primary marketing message or call to action
    <div class="jumbotron">
      <div class="container">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>
-->
 <div class="row row-offcanvas row-offcanvas-right">
 <div class="col-md-3">

   <div class="list-group">
        {% for bookClass in bookClassList %}
            <a href="{{ url_for('book_blueprint.booklist',bookClassId=bookClass.bookClassId)}}" class="list-group-item text-center ">{{bookClass.bookClassName}}</a>
        {% endfor %}
   </div>
 </div>
   <div class="col-md-9">
    <div id="ishareCarousel">
   <!-- Carousel ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="http://www.ishareread.com/res/images/index_gg/0.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
                <!--
              <h1>Example headline.</h1>
              <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
              -->
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="http://www.ishareread.com/res/images/index_gg/4.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
                 <!--
              <h1>Another example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
              -->
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="http://www.ishareread.com/res/images/index_gg/1.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
                <!--
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
              -->
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->
    </div>
   </div>
 </div>
    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->
  <div class="row featurette">
  </div>
    <div class="">
      <!-- Three columns of text below the carousel -->
       <div class="panel panel-default">
           <div class="panel-body">
              <div class="row">
                {% for book in newBooks%}
                <div class="col-md-1-5">
                    <div class="index_newbook">
                      <img src=" {{ book.bookImage }}" width="180" height="250" alt="{{ book.bookName }}" onerror="javascript:this.src='/res/images/nobook.jpg'">
                        <p><a href="{{ url_for('book_blueprint.getbookdetail',bookId=book.bookId)}}">{{ book.bookName }}</a></p>
                      <p>{{ book.bookAuthor|safe}}</p>
                    </div>
                </div><!-- /.col-lg-4 -->
                {% endfor %}
              </div><!-- /.row -->
           </div>
       </div>

<div class="row">
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    精品书籍
                </h3>
            </div>
           <div class="panel-body">
               <ul class="contentdiv_ul">
                {% for goodbook in goodBooks%}
                 <li>
                     <a href="{{ url_for('book_blueprint.getbookdetail',bookId=goodbook.bookId)}}">
                           <img width="140px" height="196px" src="{{ goodbook.bookImage }}" alt="{{ goodbook.bookName }}" onerror="javascript:this.src='/res/images/nobook.jpg'">
                     </a>
                     <h5><a href="{{ url_for('book_blueprint.getbookdetail',bookId=goodbook.bookId)}}">{{ goodbook.bookName }}</a></h5>
                     <p>{{ goodbook.bookAuthor|safe}}</p>
                 </li>
                 {% endfor %}
	            </ul>
           </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    乐享榜
                </h3>
            </div>
           <div class="panel-body">
                 <ul class="hotshare_ul">
                     {% for sharehotbook in shareHotBooks%}
                    <li >
                        <img src="{{ sharehotbook.bookImage }}" alt="{{ sharehotbook.bookName }}" onerror="javascript:this.src='/res/images/nobook.jpg'">
                        <div ><h5><a href="{{ url_for('book_blueprint.getbookdetail',bookId=sharehotbook.bookId)}}">{{ sharehotbook.bookName }}</a></h5>
                        {{ sharehotbook.bookShareEbookcount }}人在分享电子书<br>
                        {{ sharehotbook.bookShareBookcount }}人在分享纸质书</div>
                    </li>
                     {% endfor %}
                </ul>
           </div>
        </div>
    </div>
</div>

{% endblock %}


{% block scripts %}
{{ super() }}
{% endblock %}